name: a11ymatters
description: Documenting everything through the journey of learning web accessibility.
url: http://a11ymatters.com
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: /a11ymatters

links:
 - title: Home
   url: /
   id: /
 - title: Articles
   url: /articles
   id: /articles/
 - title: Patterns
   url: /patterns
   id: /patterns/
 # - title: Mockup 2 Markup
   # url: /mockup-to-markup/
   # id: /mockup-to-markup/
 - title: Terms
   url: /terms/
   id: /terms/
 - title: FAQ
   url: /faq
   id: /faq/


kramdown:
  auto_ids: true